server:
  port: ${PORT:8080}  # Usa la variable de entorno PORT, por defecto 8080


spring:
  datasource:
    url: jdbc:postgresql://dpg-d4dkp1jipnbc73a4mml0-a.frankfurt-postgres.render.com:5432/pokemondb_6ha6
    username: pokemondb_6ha6_user
    password: LzkD6M4Dwbc5lILrLAzlukApyeXb56RX
  jpa:
    hibernate:
      ddl-auto: validate   # usamos Flyway para crear/sembrar
    open-in-view: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
