server:
  port: ${PORT:8080}  # Spring Boot usar√° la variable PORT de Render, por defecto 8080 en local

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}          # Inyectada desde Render
    username: ${SPRING_DATASOURCE_USERNAME} # Inyectada desde Render
    password: ${SPRING_DATASOURCE_PASSWORD} # Inyectada desde Render
  jpa:
    hibernate:
      ddl-auto: validate   # usamos Flyway para crear/sembrar
    open-in-view: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
